import Navbar from "@/components/Navbar";
import Providers from "@/Providers";
import SessionProvider from "@/utils/SessionProvider";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import "./globals.css";
import { StoreProviders } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang='en'>
      <body className={inter.className}>
        <StoreProviders>
          <SessionProvider session={session}>
            <div className='mx-auto max-w-screen text-2xl gap-2 mb-10'>
              <Navbar />
              <Providers>{children}</Providers>
            </div>
          </SessionProvider>
        </StoreProviders>
      </body>
    </html>
  );
}
