#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Running Git Hooks'

# Build
echo '🔨 Running build...'
npm run build || (
    echo "\n⛔️ Build failed. Please fix the issues and try committing again. ⛔️";
    exit 1;
)

echo '✅ Build successful'

# If everything is good, proceed with lint-staged and commit
echo '⌛️ committing...'
